export const navData=[
    {
        xs:1,
        path:"/home",
        label:"Home"
    },
    {
        xs:1,
        path:"/basics",
        label:"Basic's"
    },
    {
        xs:2,
        path:"/html",
        label:"HTML"
    },
    {
        xs:2,
        path:"/css",
        label:"CSS"
    },
    {
        xs:2,
        path:"/js",
        label:"JavaScript"
    },
    {
        xs:2,
        path:"/react",
        label:"React.js"
    },
    {
        xs:2,
        path:"/mongo",
        label:"MongoDB"
    },
    {
        xs:2,
        path:"/express",
        label:"Express"
    },
    {
        xs:2,
        path:"/redux",
        label:"Redux"
    },
    {
        xs:2,
        path:"/node",
        label:"Node.js"
    },
    {
        xs:3,
        path:"/qa",
        label:"Question and Answers"
    },
    {
        xs:2,
        path:"/doubt",
        label:"DOUBT'S"
    },
    {
        xs:1.2,
        path:"/project",
        label:"Project's"
    },
    {
        xs:1,
        path:"/more",
        label:"More"
    }
]